export const categories = [
  {
    logo: "/categories/life.jfif",
    name: "Philosophies",
    topics: "3",
    link: "/wiki/philosophies",
    article1_logo: "/images/stoicism.jfif",
    article1_title: "Stoicism",
    article1_link: "stoicism",
    article2_logo: "/images/nihilism.jfif",
    article2_title: "Nihilism",
    article2_link: "nihilism",
  },
  {
    logo: "/categories/biotehnology.jfif",
    name: "Biotehnology",
    topics: "3",
    link: "/wiki/biotechnology",
    article1_logo: "/imagasces/",
    article1_title: "csa",
    article1_link: "",
    article2_logo: "cascaca",
    article2_title: "asca",
    article2_link: "csa",
  },
  {
    logo: "/categories/cryptocurrency.png",
    name: "Blockchain an  d cryptocurrency",
    topics: "12",
    link: "/wiki/blockchain-and-cryptocurrency",
    article1_logo: "/images/",
    article1_title: "ascac",
    article1_link: "",
    article2_logo: "AS",
    article2_title: "CSA",
    article2_link: "csa",
  },
  {
    logo: "/categories/quantum-computing.png",
    name: "Quantum Computing",
    topics: "3",
    link: "/wiki/quantum-computing",
    article1_logo: "/images/",
    article1_title: "ascac",
    article1_link: "",
    article2_logo: "AS",
    article2_title: "CSA",
    article2_link: "csa",
  },
];
